# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Desk Buddy' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Desk Buddy
  pod "SwiftChart"

  target 'Desk BuddyTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Desk BuddyUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
